//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RefactorThis.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Responses {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Responses() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RefactorThis.Domain.Resources.Responses", typeof(Responses).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invoice was already fully paid.
        /// </summary>
        public static string Invoice_Already_FullyPaid {
            get {
                return ResourceManager.GetString("Invoice_Already_FullyPaid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Final partial payment received, invoice is now fully paid.
        /// </summary>
        public static string Invoice_Final_Payment_Received {
            get {
                return ResourceManager.GetString("Invoice_Final_Payment_Received", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invoice is now fully paid.
        /// </summary>
        public static string Invoice_FullyPaid {
            get {
                return ResourceManager.GetString("Invoice_FullyPaid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to No payment needed.
        /// </summary>
        public static string Invoice_NoPayment_Needed {
            get {
                return ResourceManager.GetString("Invoice_NoPayment_Needed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Another partial payment received, still not fully paid.
        /// </summary>
        public static string Invoice_Partial_Payment_Received {
            get {
                return ResourceManager.GetString("Invoice_Partial_Payment_Received", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invoice is now partially paid.
        /// </summary>
        public static string Invoice_Partially_Paid {
            get {
                return ResourceManager.GetString("Invoice_Partially_Paid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The payment is greater than the partial amount remaining.
        /// </summary>
        public static string Invoice_Payment_Greater_Than_Amount_Remaining {
            get {
                return ResourceManager.GetString("Invoice_Payment_Greater_Than_Amount_Remaining", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The payment is greater than the invoice amount.
        /// </summary>
        public static string Invoice_Payment_Greater_Than_Invoice_Amount {
            get {
                return ResourceManager.GetString("Invoice_Payment_Greater_Than_Invoice_Amount", resourceCulture);
            }
        }
    }
}
